version: "3.7"
services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    env_file:
      - php-server/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  php-server:
    build:
      args:
        user: fruit
        uid: 1000
      context: .
      dockerfile: ./php-server/Dockerfile
    container_name: php-server
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./php-server:/var/www
    networks:
      - app_network
    depends_on:
      mysql-db:
        condition: service_healthy
    entrypoint:
      - /var/www/docker-entrypoint.sh

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - app_network
    depends_on:
      - php-server

  vue-client:
    image: node:18-bullseye
    container_name: vue-client
    restart: unless-stopped
    working_dir: /usr/src/app
    expose:
      - 5173
    ports:
      - "5173:5173" 
    volumes:
      - ./vue-client:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app_network
    entrypoint:
      - /usr/src/app/docker-entrypoint.sh
    tty: true

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  node_modules:
    driver: local
